# Generated by Django 4.1.5 on 2023-08-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
    ]
