# Generated by Django 4.1.5 on 2023-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerHeader',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='bannerImage',
            field=models.ImageField(blank=True, upload_to='images/news/banner/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bannerText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/news/posts/'),
        ),
    ]
