# Generated by Django 4.1.5 on 2023-02-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_bannerheader_alter_post_bannerimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(default=1, upload_to='images/news/posts/'),
            preserve_default=False,
        ),
    ]
