# Generated by Django 4.1.5 on 2023-02-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsimage_image_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='news',
        ),
    ]
