# Generated by Django 4.1.5 on 2023-02-18 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_previewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerImage',
            field=models.ImageField(blank=True, upload_to='images/news/posts/%y/%m/%d/banner/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 18)),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='images/news/posts/%y/%m/%d/preview/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/news/posts/%y/%m/%d/images/'),
        ),
    ]
