# Generated by Django 4.1.5 on 2023-02-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/posts/%y/%m/%d/gallery/'),
        ),
    ]
