# Generated by Django 4.1.5 on 2023-03-11 22:47

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerImage',
            field=models.ImageField(blank=True, upload_to=news.models.get_news_banner_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to=news.models.get_news_preview_path),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=news.models.get_news_gallery_path),
        ),
    ]
