# Generated by Django 4.1.5 on 2023-03-12 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_post_bannerimage_alter_post_previewimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 13)),
        ),
    ]
