# Generated by Django 4.1.5 on 2023-04-02 23:59

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.date(2023, 4, 3))),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_news_banner_path)),
                ('header', models.CharField(blank=True, max_length=256)),
                ('text', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 4, 3))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
