# Generated by Django 4.1.5 on 2023-02-18 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 18)),
        ),
    ]
