# Generated by Django 4.1.5 on 2023-04-13 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
