# Generated by Django 4.1.5 on 2023-08-28 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_information_date_alter_mainbanner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 28)),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 28)),
        ),
    ]
