# Generated by Django 4.1.5 on 2023-08-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_information_date_alter_mainbanner_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentquestions',
            options={'verbose_name': 'Частый вопрос', 'verbose_name_plural': 'Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Инфорация на главном баннере', 'verbose_name_plural': 'Инфорация на главном баннере'},
        ),
    ]
