# Generated by Django 4.1.5 on 2023-03-12 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '__first__'),
        ('main', '0011_alter_information_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_news_banner_path)),
                ('header', models.CharField(blank=True, max_length=256)),
                ('text', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date(2023, 3, 13))),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
    ]
