# Generated by Django 4.1.5 on 2023-03-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '__first__'),
        ('main', '0012_mainbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
    ]
