# Generated by Django 4.1.5 on 2023-03-15 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_mainbanner_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbanner',
            name='post',
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
