# Generated by Django 4.1.5 on 2023-04-02 23:59

import about.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('previewImage', models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to='images/AdditionalActivity/')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('previewImage', models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to='images/AreaOfActivity/')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Regulation', 'Уставные документы Автономной Некоммерческой организации «Центр помощи, поддержки, социальной и трудовой адаптации»'), ('Other', 'Прочие ДОКУМЕНТЫ')], max_length=256)),
                ('previewImage', models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to=about.models.get_docs_preview_path)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, default='images/vacancy/default_vac.png', upload_to='images/vacancy/%y/%m/%d')),
                ('requirements', models.TextField()),
                ('experience', models.TextField()),
                ('conditions', models.TextField()),
                ('wages', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=about.models.get_news_gallery_path)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.document')),
            ],
        ),
    ]
