# Generated by Django 4.1.5 on 2023-02-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('previewImage', models.ImageField(blank=True, default='docs/images/default_doc.png', upload_to='docs/images')),
                ('type', models.CharField(choices=[('AA', 'Дополнительные виды деятельности'), ('AoA', 'Направления деятельности'), ('Reg', 'Уставные документы Автономной Некоммерческой организации «Центр помощи, поддержки, социальной и трудовой адаптации»'), ('O', 'Прочие ДОКУМЕНТЫ')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('requirements', models.TextField()),
                ('experience', models.TextField()),
                ('conditions', models.TextField()),
                ('wages', models.FloatField()),
            ],
        ),
    ]
