# Generated by Django 4.1.5 on 2023-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Regulation', 'Уставные документы Автономной Некоммерческой организации «Центр помощи, поддержки, социальной и трудовой адаптации»'), ('Other', 'Прочие ДОКУМЕНТЫ'), ('Reporting', 'Отчетность')], max_length=256),
        ),
    ]
