# Generated by Django 4.1.5 on 2023-08-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalactivity',
            options={'verbose_name': 'Дополнительная цель деятельности', 'verbose_name_plural': 'Дополнительные цели деятельности'},
        ),
        migrations.AlterModelOptions(
            name='areaofactivity',
            options={'verbose_name': 'Направление деятельности', 'verbose_name_plural': 'Направления деятельности'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
