# Generated by Django 4.1.5 on 2023-01-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_typeofdocument_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('requirements', models.TextField()),
                ('experience', models.TextField()),
                ('conditions', models.TextField()),
                ('wages', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AreasOfActivity',
            new_name='AreaOfActivity',
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
