# Generated by Django 4.1.5 on 2023-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_delete_areaofactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='previewImage',
            field=models.ImageField(blank=True, default='docs/images/default_doc.png', upload_to='docs/images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Additional_activity', 'Дополнительные виды деятельности'), ('AreaOfActivity', 'Направления деятельности'), ('Regulation', 'Уставные документы Автономной Некоммерческой организации «Центр помощи, поддержки, социальной и трудовой адаптации»'), ('Other', 'Прочие ДОКУМЕНТЫ')], max_length=256),
        ),
    ]
