# Generated by Django 4.1.5 on 2023-02-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_document_previewimage_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='previewImage',
            field=models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to='images/docs/%y/%m/%d'),
        ),
    ]
