# Generated by Django 4.1.5 on 2023-02-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_document_previewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, default='images/vacancy/default_vac.png', upload_to='images/vacancy/%y/%m/%d'),
        ),
    ]
