# Generated by Django 4.1.5 on 2023-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_vacancy_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('previewImage', models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to='images/AdditionalActivity/')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('previewImage', models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to='images/AreaOfActivity/')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Regulation', 'Уставные документы Автономной Некоммерческой организации «Центр помощи, поддержки, социальной и трудовой адаптации»'), ('Other', 'Прочие ДОКУМЕНТЫ')], max_length=256),
        ),
    ]
