# Generated by Django 4.1.5 on 2023-03-13 02:04

import about.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_additionalactivity_areaofactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.AlterField(
            model_name='document',
            name='previewImage',
            field=models.ImageField(blank=True, default='images/docs/default_doc.png', upload_to=about.models.get_docs_preview_path),
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=about.models.get_news_gallery_path)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.document')),
            ],
        ),
    ]
